"""Constants for the ALLPOWERS BLE integration."""

from typing import Final

DOMAIN: Final = "allpowers_ble"
MANUFACTURER: Final = "ALLPOWERS"
DEFAULT_NAME: Final = "ALLPOWERS power station"

CONFIG_ENTRY_VERSION: Final = 1
CONFIG_ENTRY_MINOR_VERSION: Final = 1

SERVICE_UUID: Final = "0000fff0-0000-1000-8000-00805f9b34fb"
NOTIFY_UUID: Final = "0000fff1-0000-1000-8000-00805f9b34fb"
WRITE_UUID: Final = "0000fff2-0000-1000-8000-00805f9b34fb"

CONF_DEVICE_NAME: Final = "device_name"
CONF_STATUS_INTERVAL: Final = "status_interval"
CONF_STALE_TIMEOUT: Final = "stale_timeout"
CONF_WATCHDOG_TIMEOUT: Final = "watchdog_timeout"
CONF_RECONNECT_MAX_DELAY: Final = "reconnect_max_delay"
CONF_SETTINGS_STALE_TIMEOUT: Final = "settings_stale_timeout"
CONF_SETTINGS_KEEPALIVE: Final = "settings_keepalive"
CONF_SETTINGS_KEEPALIVE_INTERVAL: Final = "settings_keepalive_interval"
CONF_ENABLE_CAR_CHARGER: Final = "enable_car_charger"

DEFAULT_STATUS_INTERVAL: Final = 20.0
DEFAULT_STALE_TIMEOUT: Final = 30.0
DEFAULT_WATCHDOG_TIMEOUT: Final = 45.0
DEFAULT_RECONNECT_MAX_DELAY: Final = 60.0
DEFAULT_SETTINGS_STALE_TIMEOUT: Final = 600.0
DEFAULT_SETTINGS_KEEPALIVE: Final = False
DEFAULT_SETTINGS_KEEPALIVE_INTERVAL: Final = 540.0
DEFAULT_ENABLE_CAR_CHARGER: Final = False

MIN_STATUS_INTERVAL: Final = 10.0
MAX_STATUS_INTERVAL: Final = 120.0
MIN_STALE_TIMEOUT: Final = 15.0
MAX_STALE_TIMEOUT: Final = 300.0
MIN_WATCHDOG_TIMEOUT: Final = 25.0
MAX_WATCHDOG_TIMEOUT: Final = 600.0
MIN_RECONNECT_MAX_DELAY: Final = 5.0
MAX_RECONNECT_MAX_DELAY: Final = 300.0
MIN_SETTINGS_STALE_TIMEOUT: Final = 60.0
MAX_SETTINGS_STALE_TIMEOUT: Final = 3600.0
MIN_SETTINGS_KEEPALIVE_INTERVAL: Final = 60.0
MAX_SETTINGS_KEEPALIVE_INTERVAL: Final = 540.0

INITIAL_CONNECT_TIMEOUT: Final = 20.0
INITIAL_DATA_TIMEOUT: Final = 25.0
WRITE_TIMEOUT: Final = 10.0
COMMAND_REFRESH_DELAY: Final = 0.35
OUTPUT_SHADOW_TIMEOUT: Final = 5.0
SETTINGS_SHADOW_TIMEOUT: Final = 10.0

ATTRIBUTION: Final = "Data provided locally by the ALLPOWERS power station"
